import Head from 'next/head'
import { formatDistanceToNow, formatRelative, parseISO } from 'date-fns';
import { zonedTimeToUtc } from 'date-fns-tz';
import ptBR from 'date-fns/locale/pt-BR';
import styles from '../styles/Home.module.css'
import { useState } from 'react';


export default function Home({holidays}) {
  const today = new Date();
  function findClosestHoliday() {
    const closest = holidays.reduce((prev, curr) => {
      const prevDate = new Date(prev.date);
      const currDate = new Date(curr.date);
      return (Math.abs(currDate - today) < Math.abs(prevDate - today) ? curr : prev);
    });
    return closest;
  }
  
  const closestHoliday = findClosestHoliday();
  const nextHolidayTZ = zonedTimeToUtc( closestHoliday.date, 'America/Sao_Paulo');
  const nextHoliday = formatDistanceToNow(new Date(nextHolidayTZ), {locale: ptBR});

  let random = Math.floor(Math.random() * 8) + 1;
  const [classNumber, setClassNumber] = useState(random);

  setInterval(() => {
    random = (Math.floor(Math.random() * 8) + 1) ;
    setClassNumber(random);
  }, 60000)
    
  return (
    <div className={`content g${classNumber}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.bg}>
        <div className={styles.card}>
          <p className={styles.holiday}>O próximo feriado será o de</p>
          <p className={styles.holiday}><b>{closestHoliday.name}</b></p>
        </div>
      </div>

      <div className="bg-image">
        <h1 className={styles.distance}>{nextHoliday ? `em ${nextHoliday}` : 'amanhã'}</h1>
      </div>
    </div>
  )
}
  
export async function getStaticProps(){
  const year = new Date().getFullYear();
  const holidays = await fetch(`https://brasilapi.com.br/api/feriados/v1/${year}`);
  const holidaysInJson = await holidays.json()
  
  return {
    props: {
      holidays: holidaysInJson
    }
  }
  
}
    