import Head from 'next/head'
import { formatDistanceToNow, formatRelative, parseISO } from 'date-fns';
import { zonedTimeToUtc } from 'date-fns-tz';
import ptBR from 'date-fns/locale/pt-BR';
import styles from '../styles/Home.module.css'


export default function Home({holidays}) {
  const today = new Date();
  function findClosestHoliday() {
    const closest = holidays.reduce((prev, curr) => {
      const prevDate = new Date(prev.date);
      const currDate = new Date(curr.date);
      return (Math.abs(currDate - today) < Math.abs(prevDate - today) ? curr : prev);
    });
    return closest;
  }
  
  const closestHoliday = findClosestHoliday();
  const nextHolidayTZ = zonedTimeToUtc( closestHoliday.date, 'America/Sao_Paulo');
  const nextHoliday = formatDistanceToNow(new Date(nextHolidayTZ), {locale: ptBR});
    
  return (
    <div className={styles.bg}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.card}>
        <p className={styles.holiday}>{closestHoliday.name}</p>
        <h2 className={styles.phrase}>O próximo feriado será em</h2>
        <h1 className={styles.distance}>{nextHoliday}</h1>
      </div>
    </div>
  )
}
  
export async function getStaticProps(){
  const year = new Date().getFullYear();
  const holidays = await fetch(`https://brasilapi.com.br/api/feriados/v1/${year}`);
  const holidaysInJson = await holidays.json()
  
  return {
    props: {
      holidays: holidaysInJson
    }
  }
  
}
    